name: Build

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: pip3 install --break-system-packages setuptools
      - run: npm ci

      - run: npm run pack:mac
        env:
          GH_TOKEN: "skip"

      - uses: actions/upload-artifact@v4
        with:
          name: Music-AI-macOS
          path: release/*.dmg

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: python -m pip install setuptools
      - run: npm ci

      - run: npm run pack:win
        env:
          GH_TOKEN: "skip"

      - uses: actions/upload-artifact@v4
        with:
          name: Music-AI-Windows
          path: release/*.exe
